
string:
	g++ -std=c++11 -o string string.cpp

vector:
	g++ -std=c++11 -o vector vector.cpp

clean:
	rm -rf *.o string vector
	# find . -type f -print0 | xargs -0 file --mime-type | grep -i 'charset=binary' | cut -d: -f1 | xargs rm -f
